master = <<-SHELL
                  sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                  sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --node-ip 192.168.56.110 --flannel-iface eth1" sh -
              SHELL
agent = <<-SHELL
                  sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                  sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.56.110:80 INSTALL_K3S_EXEC="agent --node-ip 192.168.56.111 --flannel-iface eth1" sh -
              SHELL

Vagrant.configure(2) do |config|
	config.vm.box = "centos/8"
	config.vm.box_url = "../CentOS-8-Vagrant-8.3.2011-20201204.2.x86_64.vagrant-virtualbox.box"

	config.vm.define "meunostuS" do |server|
		server.vm.hostname = "meunostuS"
		server.vm.network "private_network", ip: "192.168.56.110
		config.vm.network "forwarded_port", guest: 80, host: 80
		server.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuS"]
			v.gui = false
			v.memory = "512"
			v.cpus = 1
		end
		server.vm.provision "shell", inline: master
	end
	config.vm.define "meunostuSW" do |worker|
		worker.vm.hostname = "meunostuSW"
		worker.vm.network "private_network", ip: "192.168.56.111"
        config.vm.network "forwarded_port", guest: 81, host: 81
		worker.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuSW"]
			v.gui = false
			v.memory = "512"
			v.cpus = 1
		end
		worker.vm.provision "shell", inline: agent
	end
end
