master = <<-SHELL
                  cat /home/vagrant/.ssh/my_authorized_keys >> /home/vagrant/.ssh/authorized_keys
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --node-name meunostuS --node-ip 192.168.42.110 --flannel-iface enp0s8" sh -
                  cat /var/lib/rancher/k3s/server/node-token > /vagrant/token
                  /usr/local/bin/kubectl get nodes -o wide
                  ip addr show enp0s8
              SHELL
agent = <<-SHELL
                  cat /home/vagrant/.ssh/my_authorized_keys >> /home/vagrant/.ssh/authorized_keys
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.42.110 INSTALL_K3S_EXEC="agent --node-ip 192.168.42.111:2222 --flannel-iface enp0s8" sh -
                  /usr/local/bin/kubectl get nodes -o wide
              SHELL

Vagrant.configure(2) do |config|
	config.vm.box = "geerlingguy/centos7"
  config.vm.box_url = "../packer-centos-7-x86_64.box"
  # config.vm.box = "centos/8"
	# config.vm.box_url = "../CentOS-8-Vagrant-8.0.1905-1.x86_64.vagrant-virtualbox.box"

	config.vm.define "meunostuS" do |server|
		server.vm.hostname = "meunostuS"
		server.vm.network "private_network", ip: "192.168.42.110"
		server.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/my_authorized_keys"
    server.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuS"]
      v.auto_nat_dns_proxy = false
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.gui = false
			v.memory = "1024"
			v.cpus = 2
		end
		server.vm.provision "shell", inline: master
	end
	config.vm.define "meunostuSW" do |worker|
		worker.vm.hostname = "meunostuSW"
		worker.vm.network "private_network", ip: "192.168.42.111"
        worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/my_authorized_keys"
		worker.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuSW"]
      v.auto_nat_dns_proxy = false
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.gui = false
			v.memory = "512"
			v.cpus = 1
		end
		worker.vm.provision "shell", inline: agent
	end
end


# master = <<-SHELL
#                   curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --node-name meunostuS --node-ip 192.168.42.110 --flannel-iface eth1" sh -
#                   cat /var/lib/rancher/k3s/server/node-token > /vagrant/token
#               SHELL

# Vagrant.configure(2) do |config|
#   config.vm.box = "geerlingguy/centos7"
#   config.vm.box_url = "../packer-centos-7-x86_64.box"
#   # config.vm.box_url = "../CentOS-8-Vagrant-8.3.2011-20201204.2.x86_64.vagrant-virtualbox.box"

#   config.vm.define "meunostuS" do |server|
#     server.vm.hostname = "meunostuS"
#     server.vm.network "private_network", ip: "192.168.42.110"
#     server.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/my_authorized_keys"
#     server.vm.provider "virtualbox" do |v|
#       v.customize ["modifyvm", :id, "--name", "meunostuS"]
#       v.auto_nat_dns_proxy = false
#             v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
#             v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#       v.gui = false
#       v.memory = "512"
#       v.cpus = 1
#     end
#     server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
#     # server.vm.synced_folder ".", "/vagrant"
#     server.vm.provision "shell", inline: master
#   end
# end
