script_server = <<-SHELL
                  sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                  sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="agent --node-ip 192.168.56.110" sh -
              SHELL
script_agent = <<-SHELL
                  sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
                  sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
                  curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --node-ip 192.168.56.111" sh -
               SHELL

Vagrant.configure(2) do |config|
	config.vm.box = "centos/8"
	config.vm.box_url = "../CentOS-8-Vagrant-8.3.2011-20201204.2.x86_64.vagrant-virtualbox.box"

	config.vm.define "meunostuS" do |control|
		control.vm.hostname = "meunostuS"
		control.vm.network "private_network", bridge: "en0: Ethernet", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuS"]
			v.gui = false
			v.memory = "512"
			v.cpus = 1
		end
		control.vm.provision "shell", inline: script_agent
	end
	config.vm.define "meunostuSW" do |control|
		control.vm.hostname = "meunostuSW"
		control.vm.network "private_network", bridge: "en0: Ethernet", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |v|
			v.customize ["modifyvm", :id, "--name", "meunostuSW"]
			v.gui = false
			v.memory = "512"
			v.cpus = 1
		end
		control.vm.provision "shell", inline: script_server
	end
end